name: Prefixer
main: com.sparkedia.valrix.Prefixer.Prefixer
version: 1.8
author: Valrix
description: Sets custom prefix to individual players
commands:
  prefix:
    description: Give player a prefix
    usage: |
      <> = Required [] = Optional
      /<command> list
      /<command> <prefix>
      /<command> <name> [prefix]