name: Prefixer
main: com.sparkedia.valrix.Prefixer.Prefixer
version: 2.3
author: Valrix
description: Sets custom prefix to individual players
commands:
  prefix:
    description: Give player a prefix
    usage: |
      <> = Required [] = Optional
      /<command> list
      /<command> [colorcode]<prefix>
      /<command> <name> [colorcode][prefix]